version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD:  root
      MYSQL_DATABASE:  user_db
    ports:
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
